
## Where the vocab(s) will be written
src_vocab: data/vocab/ro_port_span_vocab.txt
tgt_vocab: data/vocab/italian_vocab.txt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: data/concatenate_ro_port_span_input.txt
        path_tgt: data/italian_training_res.txt
    valid:
        path_src: data/concatenate_ro_port_span_val.txt
        path_tgt: data/italian_val_res.txt

save_model: models/ro_po_sp/model
save_checkpoint_steps: 200
train_steps: 10000
valid_steps: 500