
## Where the vocab(s) will be written
src_vocab: data/vocab/french_span_vocab.txt
tgt_vocab: data/vocab/italian_vocab.txt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: data/concatenate_fre_sp_input.txt
        path_tgt: data/italian_training_res.txt
    valid:
        path_src: data/concatenate_fre_sp_val.txt
        path_tgt: data/italian_val_res.txt

save_model: mopdels/fre_sp/model
save_checkpoint_steps: 200
train_steps: 10000
valid_steps: 500