
## Where the vocab(s) will be written
src_vocab: data/vocab/spanish_vocab.txt
tgt_vocab: data/vocab/italian_vocab.txt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: data/spanish_training_res.txt
        path_tgt: data/italian_training_res.txt
    valid:
        path_src: data/spanish_val_res.txt
        path_tgt: data/italian_val_res.txt

save_model: models/sp_it/model
save_checkpoint_steps: 100
train_steps: 5000
valid_steps: 500